export const PRODUCT_SET = "PRODUCT_SET";
export const PRODUCTS_SET = "PRODUCTS_SET";

export const CATEGORY_SET = "CATEGORY_SET";
export const CATEGORIES_SET = "CATEGORIES_SET";
export const CATEGORY_STATE_CLEAR = "CATEGORY_STATE_CLEAR";
export const CATEGORY_APPEND = "CATEGORY_APPEND";
export const CATEGORY_UPDATE = "CATEGORY_UPDATE";
export const CATEGORY_UPDATE_ACTIVE = "CATEGORY_UPDATE_ACTIVE";
export const CATEGORIES_FIND = "CATEGORIES_FIND";

export const COMMON_ERROR_SET = 'COMMON_ERROR_SET'
export const COMMON_MESSAGE_SET = 'COMMON_MESSAGE_SET'
export const COMMON_LOADING_SET = 'COMMON_LOADING_SET'

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";  // Thêm action type cho logout


export const SIZE_SET = "SIZE_SET";
export const SIZES_SET = "SIZES_SET";
export const SIZE_STATE_CLEAR = "SIZE_STATE_CLEAR";
export const SIZE_APPEND = "SIZE_APPEND";
export const SIZE_UPDATE = "SIZE_UPDATE";
export const SIZE_UPDATE_ACTIVE = "SIZE_UPDATE_ACTIVE";
export const SIZES_FIND = "SIZES_FIND";
